version: 2.1
orbs:
  terraform: circleci/terraform@3.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./environment/staging
      - terraform/validate:
          path: ./environment/staging
      - terraform/fmt:
          path: ./environment/staging
      - terraform/plan:
          path: ./environment/staging
      - terraform/apply:
          path: ./environment/staging
      - terraform/destroy:
          path: ./environment/staging
    working_directory: ~/work
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
