machine:
  environment:
    S3_BUCKET: circleci-mydic
    AWS_DEFAULT_REGION: ap-northeast-1
    TERRAFORM_VER: 1.2.9

dependencies:
  override:
    - |
      if [[ ! -f ~/.local/bin/terraform ]]; then
        mkdir -p ~/.local/bin
        cd ~/.local/bin
        wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VER}/terraform_${TERRAFORM_VER}_linux_amd64.zip"
        unzip *.zip
        rm *.zip
      fi
  cache_directories:
    - ~/.local/bin

deployment:
  staging:
    branch: staging
    commands:
      - cd staging
      - terraform plan
  production:
    branch: main
    commands:
      - cd staging
      - terraform plan
